// База данных рецептов Cookify
// Всего: 110 рецептов (15 завтраков + 35 обедов + 25 ужинов + 15 перекусов + 20 десертов)

export const RECIPES_DATABASE = [
  // =================== ЗАВТРАКИ (15) ===================
  {
    id: 1,
    title: "Овсянка с бананом",
    time: "10",
    calories: 280,
    type: "завтрак",
    diet: "веган",
    cuisine: "русская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["овсянка", "банан", "молоко растительное", "мёд"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 2,
    title: "Омлет с овощами",
    time: "15",
    calories: 220,
    type: "завтрак",
    diet: "низкокалорийное",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["быстро", "низкокалорийное"],
    ingredients: ["яйца", "помидоры", "перец", "лук", "зелень"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 3,
    title: "Греческий йогурт с мёдом",
    time: "5",
    calories: 180,
    type: "завтрак",
    diet: "",
    cuisine: "греческая",
    difficulty: "легкий",
    tags: ["быстро"],
    ingredients: ["греческий йогурт", "мёд", "орехи", "ягоды"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 4,
    title: "Смузи с ягодами",
    time: "10",
    calories: 200,
    type: "завтрак",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["ягоды замороженные", "банан", "молоко растительное", "мёд"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 5,
    title: "Тосты с авокадо",
    time: "10",
    calories: 250,
    type: "завтрак",
    diet: "веган",
    cuisine: "мексиканская",
    difficulty: "легкий",
    tags: ["веган", "популярное"],
    ingredients: ["хлеб", "авокадо", "лимон", "соль", "перец"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 6,
    title: "Сырники классические",
    time: "25",
    calories: 320,
    type: "завтрак",
    diet: "",
    cuisine: "русская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["творог", "яйца", "мука", "сахар", "ванилин"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 7,
    title: "Арепас с яйцом",
    time: "30",
    calories: 350,
    type: "завтрак",
    diet: "",
    cuisine: "венесуэльская",
    difficulty: "средний",
    tags: [],
    ingredients: ["кукурузная мука", "вода", "соль", "яйца", "сыр"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 8,
    title: "Конгри",
    time: "35",
    calories: 380,
    type: "завтрак",
    diet: "",
    cuisine: "кубинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["рис", "чёрная фасоль", "лук", "чеснок", "специи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 9,
    title: "Фул медамес",
    time: "40",
    calories: 290,
    type: "завтрак",
    diet: "веган",
    cuisine: "египетская",
    difficulty: "средний",
    tags: ["веган"],
    ingredients: ["бобы", "чеснок", "лимон", "кумин", "оливковое масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 10,
    title: "Чечевичная каша",
    time: "30",
    calories: 260,
    type: "завтрак",
    diet: "веган",
    cuisine: "индийская",
    difficulty: "легкий",
    tags: ["веган"],
    ingredients: ["красная чечевица", "кокосовое молоко", "специи", "имбирь"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 11,
    title: "Тамагояки",
    time: "15",
    calories: 200,
    type: "завтрак",
    diet: "",
    cuisine: "японская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["яйца", "соевый соус", "мирин", "сахар", "даши"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 12,
    title: "Кимчи ччигэ",
    time: "25",
    calories: 240,
    type: "завтрак",
    diet: "",
    cuisine: "корейская",
    difficulty: "средний",
    tags: ["острое"],
    ingredients: ["кимчи", "тофу", "свинина", "гочугару", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 13,
    title: "Буба",
    time: "35",
    calories: 340,
    type: "завтрак",
    diet: "",
    cuisine: "украинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["картофель", "грибы", "лук", "сметана", "мука"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 14,
    title: "Багель с лососем",
    time: "10",
    calories: 380,
    type: "завтрак",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["быстро"],
    ingredients: ["багель", "сливочный сыр", "копчёный лосось", "каперсы", "лук"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 15,
    title: "Шакшука",
    time: "20",
    calories: 280,
    type: "завтрак",
    diet: "",
    cuisine: "турецкая",
    difficulty: "легкий",
    tags: ["популярное"],
    ingredients: ["помидоры", "яйца", "перец", "лук", "специи"],
    instructions: ["1", "2", "3"]
  },

  // =================== ОБЕДЫ (35) ===================
  {
    id: 16,
    title: "Паста карбонара",
    time: "25",
    calories: 580,
    type: "обед",
    diet: "",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["спагетти", "бекон", "яйца", "пармезан", "чёрный перец"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 17,
    title: "Чечевичный дал",
    time: "35",
    calories: 320,
    type: "обед",
    diet: "веган",
    cuisine: "индийская",
    difficulty: "средний",
    tags: ["веган"],
    ingredients: ["красная чечевица", "кокосовое молоко", "помидоры", "специи", "имбирь"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 18,
    title: "Шашлык из курицы",
    time: "40",
    calories: 420,
    type: "обед",
    diet: "",
    cuisine: "грузинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["куриное филе", "лук", "специи", "лимон", "растительное масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 19,
    title: "Рататуй",
    time: "50",
    calories: 180,
    type: "обед",
    diet: "веган",
    cuisine: "французская",
    difficulty: "средний",
    tags: ["веган", "низкокалорийное"],
    ingredients: ["баклажаны", "кабачки", "помидоры", "перец", "травы"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 20,
    title: "Буррито с фасолью",
    time: "20",
    calories: 450,
    type: "обед",
    diet: "веган",
    cuisine: "мексиканская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["тортилья", "фасоль", "рис", "авокадо", "сальса"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 21,
    title: "Суши роллы",
    time: "60",
    calories: 350,
    type: "обед",
    diet: "",
    cuisine: "японская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["рис для суши", "нори", "рыба", "авокадо", "огурец"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 22,
    title: "Пад тай",
    time: "30",
    calories: 480,
    type: "обед",
    diet: "",
    cuisine: "тайская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["рисовая лапша", "креветки", "арахис", "соус тамаринд", "ростки"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 23,
    title: "Фалафель",
    time: "35",
    calories: 340,
    type: "обед",
    diet: "веган",
    cuisine: "греческая",
    difficulty: "средний",
    tags: ["веган"],
    ingredients: ["нут", "зелень", "специи", "чеснок", "лук"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 24,
    title: "Борщ классический",
    time: "90",
    calories: 280,
    type: "обед",
    diet: "",
    cuisine: "русская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["свёкла", "капуста", "картофель", "говядина", "томатная паста"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 25,
    title: "Хинкали",
    time: "60",
    calories: 420,
    type: "обед",
    diet: "",
    cuisine: "грузинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["мука", "говядина", "свинина", "лук", "специи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 26,
    title: "Табуле",
    time: "20",
    calories: 220,
    type: "обед",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["булгур", "петрушка", "помидоры", "лимон", "оливковое масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 27,
    title: "Кускус с овощами",
    time: "25",
    calories: 310,
    type: "обед",
    diet: "веган",
    cuisine: "марокканская",
    difficulty: "легкий",
    tags: ["веган"],
    ingredients: ["кускус", "морковь", "кабачки", "специи", "изюм"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 28,
    title: "Пельмени с говядиной",
    time: "50",
    calories: 480,
    type: "обед",
    diet: "",
    cuisine: "русская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["мука", "говядина", "лук", "специи", "вода"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 29,
    title: "Кимчи джжигэ",
    time: "30",
    calories: 260,
    type: "обед",
    diet: "",
    cuisine: "корейская",
    difficulty: "средний",
    tags: ["острое"],
    ingredients: ["кимчи", "свинина", "тофу", "гочугару", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 30,
    title: "Фо бо",
    time: "120",
    calories: 420,
    type: "обед",
    diet: "",
    cuisine: "вьетнамская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["рисовая лапша", "говядина", "бульон", "базилик", "лайм"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 31,
    title: "Тапас с хамоном",
    time: "15",
    calories: 320,
    type: "обед",
    diet: "",
    cuisine: "испанская",
    difficulty: "легкий",
    tags: ["быстро"],
    ingredients: ["хамон", "хлеб", "помидоры", "оливковое масло", "чеснок"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 32,
    title: "Мусака",
    time: "90",
    calories: 520,
    type: "обед",
    diet: "",
    cuisine: "греческая",
    difficulty: "сложный",
    tags: [],
    ingredients: ["баклажаны", "говядина", "бешамель", "помидоры", "сыр"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 33,
    title: "Чимичанга",
    time: "35",
    calories: 560,
    type: "обед",
    diet: "",
    cuisine: "мексиканская",
    difficulty: "средний",
    tags: [],
    ingredients: ["тортилья", "курица", "фасоль", "сыр", "сметана"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 34,
    title: "Ризотто с грибами",
    time: "40",
    calories: 420,
    type: "обед",
    diet: "вегетарианское",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["вегетарианское"],
    ingredients: ["рис арборио", "грибы", "пармезан", "белое вино", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 35,
    title: "Карри с кокосом",
    time: "35",
    calories: 380,
    type: "обед",
    diet: "веган",
    cuisine: "тайская",
    difficulty: "средний",
    tags: ["веган"],
    ingredients: ["кокосовое молоко", "овощи", "паста карри", "рис", "базилик"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 36,
    title: "Шакшука",
    time: "25",
    calories: 290,
    type: "обед",
    diet: "",
    cuisine: "турецкая",
    difficulty: "легкий",
    tags: ["популярное"],
    ingredients: ["помидоры", "яйца", "перец", "лук", "специи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 37,
    title: "Лагман",
    time: "80",
    calories: 520,
    type: "обед",
    diet: "",
    cuisine: "узбекская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["лапша", "говядина", "овощи", "специи", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 38,
    title: "Бибимбап",
    time: "40",
    calories: 480,
    type: "обед",
    diet: "",
    cuisine: "корейская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["рис", "овощи", "яйцо", "гочуджан", "кунжутное масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 39,
    title: "Пахлава",
    time: "90",
    calories: 450,
    type: "десерт",
    diet: "",
    cuisine: "турецкая",
    difficulty: "сложный",
    tags: [],
    ingredients: ["тесто фило", "орехи", "мёд", "масло", "специи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 40,
    title: "Энчиладас",
    time: "45",
    calories: 520,
    type: "обед",
    diet: "",
    cuisine: "мексиканская",
    difficulty: "средний",
    tags: [],
    ingredients: ["тортилья", "курица", "соус чили", "сыр", "сметана"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 41,
    title: "Гювеч",
    time: "60",
    calories: 280,
    type: "обед",
    diet: "веган",
    cuisine: "болгарская",
    difficulty: "средний",
    tags: ["веган"],
    ingredients: ["баклажаны", "перец", "помидоры", "лук", "травы"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 42,
    title: "Плов узбекский",
    time: "90",
    calories: 580,
    type: "обед",
    diet: "",
    cuisine: "узбекская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["рис", "баранина", "морковь", "лук", "зира"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 43,
    title: "Суп мисо",
    time: "15",
    calories: 80,
    type: "обед",
    diet: "веган",
    cuisine: "японская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["паста мисо", "тофу", "водоросли вакаме", "даши", "зелёный лук"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 44,
    title: "Рамен",
    time: "45",
    calories: 520,
    type: "обед",
    diet: "",
    cuisine: "японская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["рамен лапша", "бульон", "свинина", "яйцо", "водоросли нори"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 45,
    title: "Том ям",
    time: "30",
    calories: 180,
    type: "обед",
    diet: "",
    cuisine: "тайская",
    difficulty: "средний",
    tags: ["острое", "низкокалорийное"],
    ingredients: ["креветки", "галангал", "лемонграсс", "кафир лайм", "грибы"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 46,
    title: "Курица с томатами и базиликом",
    time: "30",
    calories: 420,
    type: "обед",
    diet: "",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["низкокалорийное", "популярное"],
    ingredients: ["курица", "помидоры", "базилик", "оливковое масло", "чеснок"],
    instructions: [
      "Разогрейте оливковое масло на сковороде",
      "Обжарьте нарезанную курицу до золотистой корочки (7-10 минут)",
      "Добавьте нарезанные помидоры и измельченный чеснок",
      "Тушите на среднем огне 15 минут",
      "Добавьте свежий базилик за 2 минуты до готовности",
      "Посолите и поперчите по вкусу"
    ]
  },
  {
    id: 47,
    title: "Паста с грибным соусом",
    time: "25",
    calories: 560,
    type: "обед",
    diet: "вегетарианское",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["вегетарианское"],
    ingredients: ["паста", "грибы", "сливки", "пармезан"],
    instructions: [
      "Отварите пасту в подсоленной воде согласно инструкции на упаковке",
      "Нарежьте грибы тонкими пластинками",
      "Обжарьте грибы на растительном масле до золотистого цвета",
      "Добавьте сливки и тушите 5 минут",
      "Смешайте готовую пасту с грибным соусом",
      "Посыпьте тертым пармезаном перед подачей"
    ]
  },
  {
    id: 48,
    title: "Овсяноблин с ягодами",
    time: "15",
    calories: 250,
    type: "завтрак",
    diet: "веган",
    cuisine: "русская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["овсянка", "вода", "ягоды", "мёд"],
    instructions: [
      "Измельчите овсянку в блендере до состояния муки",
      "Смешайте 3 ст.л. овсяной муки с 100 мл воды до однородности",
      "Разогрейте антипригарную сковороду",
      "Вылейте тесто и жарьте 3-4 минуты с каждой стороны",
      "Выложите на тарелку, добавьте свежие ягоды",
      "Полейте мёдом по желанию"
    ]
  },
  {
    id: 49,
    title: "Салат с авокадо",
    time: "10",
    calories: 180,
    type: "перекус",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["свежо", "летнее", "веган"],
    ingredients: ["авокадо", "помидоры", "листья салата", "оливковое масло"],
    instructions: [
      "Нарежьте авокадо кубиками",
      "Нарежьте помидоры дольками",
      "Промойте и обсушите листья салата",
      "Выложите все ингредиенты в миску",
      "Заправьте оливковым маслом и лимонным соком",
      "Посолите и поперчите по вкусу"
    ]
  },
  {
    id: 50,
    title: "Салат Цезарь",
    time: "20",
    calories: 420,
    type: "обед",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["популярное"],
    ingredients: ["салат ромэн", "курица", "пармезан", "соус цезарь", "гренки"],
    instructions: ["1", "2", "3"]
  },

  // =================== УЖИНЫ (25) ===================
  {
    id: 51,
    title: "Стейк рибай",
    time: "25",
    calories: 680,
    type: "ужин",
    diet: "",
    cuisine: "американская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["стейк рибай", "соль", "перец", "масло", "чеснок"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 52,
    title: "Лосось терияки",
    time: "30",
    calories: 480,
    type: "ужин",
    diet: "",
    cuisine: "японская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["лосось", "соус терияки", "кунжут", "зелёный лук", "рис"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 53,
    title: "Долма с мясом",
    time: "90",
    calories: 420,
    type: "ужин",
    diet: "",
    cuisine: "грузинская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["виноградные листья", "говядина", "рис", "лук", "специи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 54,
    title: "Гуакамоле с тортильями",
    time: "15",
    calories: 320,
    type: "ужин",
    diet: "веган",
    cuisine: "мексиканская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["авокадо", "помидоры", "лук", "лайм", "тортилья"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 55,
    title: "Кускус с бараниной",
    time: "60",
    calories: 620,
    type: "ужин",
    diet: "",
    cuisine: "марокканская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["кускус", "баранина", "овощи", "специи", "изюм"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 56,
    title: "Соте из кролика",
    time: "50",
    calories: 480,
    type: "ужин",
    diet: "",
    cuisine: "французская",
    difficulty: "средний",
    tags: [],
    ingredients: ["кролик", "лук", "морковь", "белое вино", "тимьян"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 57,
    title: "Котлеты по-киевски",
    time: "40",
    calories: 560,
    type: "ужин",
    diet: "",
    cuisine: "украинская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["куриное филе", "масло сливочное", "зелень", "панировочные сухари", "яйца"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 58,
    title: "Суши нигири",
    time: "50",
    calories: 380,
    type: "ужин",
    diet: "",
    cuisine: "японская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["рис для суши", "рыба свежая", "васаби", "имбирь маринованный", "нори"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 59,
    title: "Бефстроганов",
    time: "35",
    calories: 520,
    type: "ужин",
    diet: "",
    cuisine: "русская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["говядина", "лук", "грибы", "сметана", "горчица"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 60,
    title: "Паэлья с морепродуктами",
    time: "60",
    calories: 580,
    type: "ужин",
    diet: "",
    cuisine: "испанская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["рис", "креветки", "мидии", "шафран", "перец"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 61,
    title: "Кебаб адана",
    time: "35",
    calories: 520,
    type: "ужин",
    diet: "",
    cuisine: "турецкая",
    difficulty: "средний",
    tags: [],
    ingredients: ["говяжий фарш", "специи", "лук", "перец", "лаваш"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 62,
    title: "Бибимбап мясной",
    time: "40",
    calories: 520,
    type: "ужин",
    diet: "",
    cuisine: "корейская",
    difficulty: "средний",
    tags: [],
    ingredients: ["рис", "говядина", "овощи", "яйцо", "гочуджан"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 63,
    title: "Фо бо говяжий",
    time: "120",
    calories: 450,
    type: "ужин",
    diet: "",
    cuisine: "вьетнамская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["рисовая лапша", "говядина", "бульон", "базилик", "лайм"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 64,
    title: "Рататуй с курицей",
    time: "55",
    calories: 380,
    type: "ужин",
    diet: "",
    cuisine: "французская",
    difficulty: "средний",
    tags: [],
    ingredients: ["курица", "баклажаны", "кабачки", "помидоры", "травы"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 65,
    title: "Мусака с мясом",
    time: "90",
    calories: 560,
    type: "ужин",
    diet: "",
    cuisine: "греческая",
    difficulty: "сложный",
    tags: [],
    ingredients: ["баклажаны", "говядина", "бешамель", "помидоры", "сыр"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 66,
    title: "Лагман мясной",
    time: "85",
    calories: 560,
    type: "ужин",
    diet: "",
    cuisine: "узбекская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["лапша", "говядина", "овощи", "специи", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 67,
    title: "Плов с бараниной",
    time: "90",
    calories: 620,
    type: "ужин",
    diet: "",
    cuisine: "узбекская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["рис", "баранина", "морковь", "лук", "зира"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 68,
    title: "Рамен тоникоцу",
    time: "50",
    calories: 580,
    type: "ужин",
    diet: "",
    cuisine: "японская",
    difficulty: "средний",
    tags: [],
    ingredients: ["рамен лапша", "свинина", "бульон", "яйцо", "водоросли"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 69,
    title: "Том кха гай",
    time: "35",
    calories: 420,
    type: "ужин",
    diet: "",
    cuisine: "тайская",
    difficulty: "средний",
    tags: [],
    ingredients: ["курица", "кокосовое молоко", "галангал", "лемонграсс", "грибы"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 70,
    title: "Чимичанга с курицей",
    time: "40",
    calories: 580,
    type: "ужин",
    diet: "",
    cuisine: "мексиканская",
    difficulty: "средний",
    tags: [],
    ingredients: ["тортилья", "курица", "фасоль", "сыр", "сметана"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 71,
    title: "Ризотто с уткой",
    time: "50",
    calories: 620,
    type: "ужин",
    diet: "",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: [],
    ingredients: ["рис арборио", "утка", "белое вино", "пармезан", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 72,
    title: "Хинкали с говядиной",
    time: "65",
    calories: 480,
    type: "ужин",
    diet: "",
    cuisine: "грузинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["мука", "говядина", "лук", "специи", "бульон"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 73,
    title: "Тагин с говядиной",
    time: "90",
    calories: 520,
    type: "ужин",
    diet: "",
    cuisine: "марокканская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["говядина", "овощи", "специи", "чернослив", "миндаль"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 74,
    title: "Оссо буко",
    time: "120",
    calories: 680,
    type: "ужин",
    diet: "",
    cuisine: "итальянская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["телятина", "белое вино", "помидоры", "бульон", "гремолата"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 75,
    title: "Фрикадельки альбондигас",
    time: "45",
    calories: 480,
    type: "ужин",
    diet: "",
    cuisine: "испанская",
    difficulty: "средний",
    tags: [],
    ingredients: ["говяжий фарш", "хлеб", "яйцо", "томатный соус", "специи"],
    instructions: ["1", "2", "3"]
  },

  // =================== ПЕРЕКУСЫ (15) ===================
  {
    id: 76,
    title: "Хумус с овощами",
    time: "10",
    calories: 180,
    type: "перекус",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["нут", "тахини", "лимон", "чеснок", "овощи"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 77,
    title: "Энергетические батончики",
    time: "15",
    calories: 220,
    type: "перекус",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["овсянка", "орехи", "финики", "мёд", "семечки"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 78,
    title: "Крекеры с сыром",
    time: "5",
    calories: 160,
    type: "перекус",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["быстро"],
    ingredients: ["крекеры", "сыр", "виноград"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 79,
    title: "Фруктовый салат",
    time: "10",
    calories: 120,
    type: "перекус",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["яблоко", "банан", "апельсин", "киви", "ягоды"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 80,
    title: "Орехи микс",
    time: "2",
    calories: 280,
    type: "перекус",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["миндаль", "кешью", "грецкие орехи", "изюм"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 81,
    title: "Йогурт с гранолой",
    time: "5",
    calories: 200,
    type: "перекус",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["быстро"],
    ingredients: ["греческий йогурт", "гранола", "мёд", "ягоды"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 82,
    title: "Овощные палочки",
    time: "10",
    calories: 80,
    type: "перекус",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["морковь", "огурец", "перец", "сельдерей"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 83,
    title: "Сырные шарики",
    time: "15",
    calories: 240,
    type: "перекус",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["сливочный сыр", "орехи", "зелень", "чеснок"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 84,
    title: "Брускетта",
    time: "15",
    calories: 180,
    type: "перекус",
    diet: "веган",
    cuisine: "итальянская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["хлеб", "помидоры", "базилик", "чеснок", "оливковое масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 85,
    title: "Эдамаме",
    time: "10",
    calories: 120,
    type: "перекус",
    diet: "веган",
    cuisine: "японская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["эдамаме", "соль", "кунжутное масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 86,
    title: "Попкорн",
    time: "5",
    calories: 100,
    type: "перекус",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро", "низкокалорийное"],
    ingredients: ["кукуруза для попкорна", "соль", "масло"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 87,
    title: "Рисовые хлебцы с арахисовой пастой",
    time: "3",
    calories: 160,
    type: "перекус",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["рисовые хлебцы", "арахисовая паста", "банан"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 88,
    title: "Сухофрукты",
    time: "2",
    calories: 200,
    type: "перекус",
    diet: "веган",
    cuisine: "средиземноморская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["курага", "чернослив", "изюм", "инжир"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 89,
    title: "Смузи боул",
    time: "10",
    calories: 280,
    type: "перекус",
    diet: "веган",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["веган", "быстро"],
    ingredients: ["замороженные ягоды", "банан", "гранола", "кокосовая стружка"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 90,
    title: "Роллы из огурца с крем-сыром",
    time: "10",
    calories: 140,
    type: "перекус",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["быстро", "низкокалорийное"],
    ingredients: ["огурец", "сливочный сыр", "укроп", "лосось"],
    instructions: ["1", "2", "3"]
  },

  // =================== ДЕСЕРТЫ (20) ===================
  {
    id: 91,
    title: "Чизкейк нью-йорк",
    time: "90",
    calories: 520,
    type: "десерт",
    diet: "",
    cuisine: "американская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["сливочный сыр", "сахар", "яйца", "печенье", "сметана"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 92,
    title: "Тирамису классика",
    time: "40",
    calories: 450,
    type: "десерт",
    diet: "",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["маскарпоне", "савоярди", "кофе", "какао", "яйца"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 93,
    title: "Баклава греческая",
    time: "70",
    calories: 480,
    type: "десерт",
    diet: "",
    cuisine: "греческая",
    difficulty: "средний",
    tags: [],
    ingredients: ["тесто фило", "орехи", "мёд", "масло", "корица"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 94,
    title: "Моти с анко",
    time: "30",
    calories: 180,
    type: "десерт",
    diet: "веган",
    cuisine: "японская",
    difficulty: "легкий",
    tags: ["веган"],
    ingredients: ["рисовая мука моти", "сахар", "паста анко", "вода"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 95,
    title: "Манго стикки райс",
    time: "35",
    calories: 320,
    type: "десерт",
    diet: "веган",
    cuisine: "тайская",
    difficulty: "легкий",
    tags: ["веган"],
    ingredients: ["клейкий рис", "манго", "кокосовое молоко", "сахар"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 96,
    title: "Крем брюле",
    time: "60",
    calories: 380,
    type: "десерт",
    diet: "",
    cuisine: "французская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["сливки", "яичные желтки", "сахар", "ваниль"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 97,
    title: "Панна котта",
    time: "30",
    calories: 320,
    type: "десерт",
    diet: "",
    cuisine: "итальянская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["сливки", "сахар", "желатин", "ваниль", "ягоды"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 98,
    title: "Вареники вишнёвые",
    time: "50",
    calories: 380,
    type: "десерт",
    diet: "",
    cuisine: "украинская",
    difficulty: "средний",
    tags: [],
    ingredients: ["мука", "вишня", "сахар", "яйца", "сметана"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 99,
    title: "Медовик",
    time: "90",
    calories: 420,
    type: "десерт",
    diet: "",
    cuisine: "русская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["мука", "мёд", "сметана", "яйца", "сахар"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 100,
    title: "Шарлотка яблочная",
    time: "50",
    calories: 280,
    type: "десерт",
    diet: "",
    cuisine: "французская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["яблоки", "мука", "яйца", "сахар", "корица"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 101,
    title: "Торт Наполеон",
    time: "120",
    calories: 480,
    type: "десерт",
    diet: "",
    cuisine: "русская",
    difficulty: "сложный",
    tags: ["популярное"],
    ingredients: ["слоеное тесто", "сливки", "сгущёнка", "масло", "ваниль"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 102,
    title: "Чуррос с шоколадом",
    time: "30",
    calories: 380,
    type: "десерт",
    diet: "",
    cuisine: "испанская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["мука", "вода", "яйца", "сахар", "шоколад"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 103,
    title: "Эклер с кремом",
    time: "70",
    calories: 320,
    type: "десерт",
    diet: "",
    cuisine: "французская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["мука", "яйца", "сливки", "сахар", "шоколад"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 104,
    title: "Суфле шоколадное",
    time: "45",
    calories: 280,
    type: "десерт",
    diet: "",
    cuisine: "французская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["шоколад", "яйца", "сливки", "сахар", "ваниль"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 105,
    title: "Тирамису с кофе",
    time: "40",
    calories: 450,
    type: "десерт",
    diet: "",
    cuisine: "итальянская",
    difficulty: "средний",
    tags: ["популярное"],
    ingredients: ["маскарпоне", "савоярди", "эспрессо", "какао", "ликёр"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 106,
    title: "Брауни шоколадный",
    time: "40",
    calories: 420,
    type: "десерт",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: ["популярное"],
    ingredients: ["шоколад", "масло", "яйца", "мука", "сахар"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 107,
    title: "Макаронс",
    time: "90",
    calories: 220,
    type: "десерт",
    diet: "",
    cuisine: "французская",
    difficulty: "сложный",
    tags: [],
    ingredients: ["миндальная мука", "яичные белки", "сахарная пудра", "пищевые красители", "ганаш"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 108,
    title: "Пудинг шоколадный",
    time: "25",
    calories: 320,
    type: "десерт",
    diet: "",
    cuisine: "американская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["молоко", "какао", "сахар", "кукурузный крахмал", "ваниль"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 109,
    title: "Штрудель яблочный",
    time: "60",
    calories: 350,
    type: "десерт",
    diet: "",
    cuisine: "немецкая",
    difficulty: "средний",
    tags: [],
    ingredients: ["яблоки", "слоеное тесто", "изюм", "корица", "сахар"],
    instructions: ["1", "2", "3"]
  },
  {
    id: 110,
    title: "Трайфл ягодный",
    time: "30",
    calories: 380,
    type: "десерт",
    diet: "",
    cuisine: "английская",
    difficulty: "легкий",
    tags: [],
    ingredients: ["бисквит", "крем", "ягоды", "желе", "сливки"],
    instructions: ["1", "2", "3"]
  }
];
